[program:auth-pro]
command=/www/wwwroot/YOUR_SITE/backend/auth_pro
directory=/www/wwwroot/YOUR_SITE
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=10
redirect_stderr=true
stdout_logfile=/var/log/auth-pro.out.log
environment=PORT="19127",AUTO_PRO_DATA_DIR="/www/wwwroot/YOUR_SITE/backend/data"
;environment=PORT="19127",AUTO_PRO_DATA_DIR="/www/wwwroot/YOUR_SITE/backend/data",SOFTWARE_SOURCE_ADMIN_KEY="replace-me"
